name: backend CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - working-directory: ./backend
        run: |
          npm ci
          npm run lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - working-directory: ./backend
        run: |
          npm ci
          npm test


  build:
    #PR이 merge 되었을때 아래 steps을 실행하겠다.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name : executing remote ssh commands using password
        #if: github.event_name == 'pull_request'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BARBERFORCE_HOST }}
          username: ${{ secrets.BARBERFORCE_USERNAME }}
          password: ${{ secrets.BARBERFORCE_PASSWORD }}
          script: |
            cd ${{ secrets.BARBERFORCE_PATH }} && git pull
            cd ${{ secrets.BARBERFORCE_BACK_PATH }}
            mongod
            node server.js
